# Generated by Django 5.1.1 on 2024-09-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_classify_student_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='apis.classify'),
        ),
    ]
