# Generated by Django 3.2 on 2024-09-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], default=0)),
                ('card_no', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': '学生表',
                'db_table': 't_student',
            },
        ),
    ]
